# Generated by Django 6.0.1 on 2026-02-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='courses', to='tct.student'),
        ),
    ]
