# Generated by Django 6.0.1 on 2026-02-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0005_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teacher',
        ),
    ]
