# Generated by Django 6.0.1 on 2026-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0008_remove_course_student_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='courses', through='tct.Enrollment', to='tct.student'),
        ),
    ]
